= Developer Guide

[[chap-Developer_Guide-Introduction]]

== Introduction

The RichFaces framework is a rich component library for JavaServer Faces ( JSF). The framework extends the JSF framework's Ajax capabilities with advanced features for enterprise web application development.

RichFaces leverages several parts of the JSF 2 framework including lifecycle, validation, conversion facilities, and management of static and dynamic resources. The RichFaces framework includes components with built-in Ajax support and a customizable look-and-feel that can be incorporated into JSF applications.

RichFaces provides a number of advantages for enterprise web application development:

* Create complex application views using out-of-the-box components. The RichFaces user interface ( UI) library ( +rich+) contains components for adding rich interactive features to JSF applications. It extends the RichFaces framework to include a large set of Ajax-enabled components that come with extensive skinning support. Additionally, the RichFaces framework is designed to be used seamlessly with other 3d-party libraries on the same page, so you have more options for developing applications.

* Write your own customized rich components with built-in Ajax support. The Component Development Kit ( CDK), used for the RichFaces UI library creation, includes a code-generation facility and a templating facility using XHTML(extended hyper-text markup language) syntax.

* Generate binary resources on the fly. Extensions to JSF 2 resource-handling facilities can generate images, sounds, *Microsoft Excel* spreadsheets, and more during run-time.

* Create a modern rich user-interface with skinning technology. RichFaces provides a skinning feature that allows you to define and manage different color schemes and other parameters of the look and feel. It is possible to access the skin parameters from page code during run-time. RichFaces comes packaged with a number of skins to get you started, but you can also easily create your own customized skins too.

[[chap-Developer_Guide-Getting_started_with_RichFaces]]

== Getting started with RichFaces

Follow the instructions in this chapter to configure the RichFaces framework and get started with application development.

If you have existing projects that use a previous version of RichFaces, refer to the *_RichFaces Migration Guide_* .

[[sect-Developer_Guide-Getting_started_with_RichFaces-Technical_Requirements]]

=== Technical Requirements

The minimum technical requirements needed to get started with RichFaces are outlined below.

* Java Development Kit ( JDK) 6 or higher
* An application server compliant with Java Platform, Enterprise Edition 6 ( JEE6), such as JBoss Application Server 7or a servlet container coupled with a JSF implementation, such as Apache Tomcat + Mojarra 2.x.
* A compliant web browser, such as Firefox 17, Chrome 23, or Internet Explorer 9


[[sect-Developer_Guide-Getting_started_with_RichFaces-Technical_Requirements-Project_libraries_and_dependencies]]

==== Project libraries and dependencies

RichFaces library comes in form of Java archives for Core Framework and Components.

.RichFaces Libraries
* _richfaces-core-api.jar_
* _richfaces-core-impl.jar_
* _richfaces-components-api.jar_
* _richfaces-components-ui.jar_

The framework depends on third-party dependencies which can be classified to mandatory and optional (libraries enabling certain functionality).

Note that these dependencies may depend on their own runtime dependencies.

.Mandatory third-party dependencies
* Java Server Faces 2.x implementation
** _javax.faces.jar_(version +2.1.5+ or higher)
** or _myfaces-impl.jar_(version +2.1.5+ or higher)

* Google Guava
** _guava.jar_(version +10.0.1+)

* CSS Parser
** _cssparser.jar_(version +0.9.5+)

* Simple API for CSS
** _sac.jar_(version +1.3+)

.Optional third-party dependencies

* Bean validation (JSR-303) integration for client-side validation (JSR-303 API and Implementation)
** _validation-api.jar_(version +1.0.0.GA+)
** _hibernate-validator.jar_(version +4.2.0.Final+ or higher)

* Push transport library - Atmosphere (without dependencies)
** _atmosphere-runtime.jar_(version +1.0.10+)
+
(selected compatibility modules _atmosphere-compat-*.jar_may be necessary)

* Push JMS integration (JMS API and Implementation)
** _jms.jar_(version +1.1+)
** _hornetq-jms.jar_(version +2.2.7.Final+ or higher)

* Push CDI integration (CDI API and Implementation)
** _cdi-api.jar_(version +1.0-SP4+)
** _javax.inject.jar_(version +1+)
** _jsr-250-api.jar_(version +1.0+)
** _weld-servlet.jar_(version +1.1.4.Final+)

* Extended caching (EhCache)
** _ehcache.jar_(version +1.6.0+)

[NOTE]
.Dependencies for servlet containers
====
Some of dependencies are part of Java EE 6 specification and thus it is not necessary to include them in projects running on Java EE applications servers.

It is still necessary to include them on servlet containers.

Dependencies on Servlet API, JSP API and EL API are excluded since these are integral parts of both application servers and servlet containers.
====

[[sect-Developer_Guide-Getting_started_with_RichFaces-Development_environments]]

=== Development environments

RichFaces applications can be developed using a range of tools, including integrated development environments ( IDEs). This chapter covers only two such environments in detail:

* JBoss Tools, as described in <<sect-Developer_Guide-Getting_started_with_RichFaces-Creating_a_project_with_JBoss_Tools>>.
* Maven, as described in <<sect-Developer_Guide-Getting_started_with_RichFaces-Creating_a_project_with_Maven>>.


Other environments, such as Ideaor NetBeans, could also be used for RichFaces development, but are not detailed in this book.

[[sect-Developer_Guide-Getting_started_with_RichFaces-Setting_up_RichFaces]]

=== Setting up RichFaces

Follow the instructions in this section to set up the RichFaces framework and begin building applications.

. *Download RichFaces archive*
+
Download RichFaces from the JBoss RichFaces Downloads area at http://www.jboss.org/richfaces/download.html. The binary files (available in _.zip_ or _.bin.tar.gz_ archives) contain the following:
+
* compiled, ready-to-use Java Archives ( JAR files) of the RichFaces libraries
* library source JAR files
* documentation, including Java documentation and JavaScript documentation
* archetypes
* example source code

. *Unzip archive*
+
Create a new directory named _RichFaces_, then unzip the archive containing the binaries there.

[[sect-Developer_Guide-Getting_started_with_RichFaces-Creating_a_project_with_JBoss_Tools]]

=== Creating a project with JBoss Tools

Follow the procedure in this section to create a new RichFaces application with JBoss ToolsEnsure you are using the latest version of JBoss Tools.

. *Create a new project*
+
Create a new project based on the JSF 2 environment using the RichFaces 4 template. In JBoss Tools, select File+>New+>"JSF Project" from the menu. Name the project, select guilabel:[JSF 2] from the guilabel:[JSF Environment] drop-down box, and click the guibutton:[Finish] button to create the project.
+
If necessary, update the JSF 2 JAR files to the latest versions.

[[step-Developer_Guide-Creating_a_project-Add_the_RichFaces_libraries_to_the_project]]
. *Add the RichFaces libraries to the project*
+
Add <<sect-Developer_Guide-Getting_started_with_RichFaces-Technical_Requirements-Project_libraries_and_dependencies,RichFaces libraries and their mandatory dependencies>> to the project. Copy them from the location where you unzipped the RichFaces archive to the _WebContent/WEB-INF/lib/_ directory of your project in +JBoss Tools+.

[[step-Developer_Guide-Creating_a_project-Reference_the_tag_libraries]]
. *Reference the tag libraries*
+
The RichFaces tag libraries need to be referenced on each XHTML page in your project:
+
[source, XML]
----
<ui:composition xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich">
   ...
</ui:composition>

----

You are now ready to begin constructing your RichFaces applications. RichFaces components can be dragged and dropped into your application's XHTML pages from the RichFaces palette in JBoss Tools. 

[[sect-Developer_Guide-Getting_started_with_RichFaces-Creating_a_project_with_Maven]]

=== Creating a project with Maven

+Apache Maven+ is a build automation and project management tool for Java projects. Follow the instructions in this section to create a +Maven+ project for RichFaces.

[[sect-Component_Using_RichFaces_with_Maven-Setting_up_Maven]]

==== Setting up Maven

+Maven+ can be downloaded and installed from Apache's website at http://maven.apache.org/download.html. Due to the use of dependency importing, +Maven+ version 3.0.3 or above is required.

Once +Maven+ has been installed, no further configuration is required to begin building Maven projects.

[[sect-Component_Reference-Using_RichFaces_with_Maven-Using_the_RichFaces_project_archetype]]

==== Using the +RichFaces+ project archetype

A +Maven+ archetype is a template for creating projects. +Maven+ uses an archetype to generate a directory structure and files for a particular project, as well as creating _pom.xml_files that contain build instructions.

The RichFaces Component Development Kit includes a +Maven+ archetype named _richfaces-archetype-simpleapp_ for generating the basic structure and requirements for a RichFaces application project. +Maven+ can obtain the archetype from the JBoss repository at https://repository.jboss.org/nexus/content/groups/public/. The archetype is also included with the RichFaces source code in the _archetypes_directory. Follow the procedure in this section to generate a new Maven-based RichFaces project using the archetype.

. *Add required repository*
+
The details for the JBoss repository need to be added to +Maven+ so it can access the archetype. Add a profile in the _$$maven_installation_folder/conf/settings.xml$$_file under the +<profiles>+ element:
+
[source, XML]
----
<profiles>
    ...
    <profile>
        <id>jboss-public-repository</id>
        <repositories>
            <repository>
                <id>jboss-public-repository-group</id>
                <name>JBoss Public Maven Repository Group</name>
                <url>https://repository.jboss.org/nexus/content/groups/public/</url>
                <layout>default</layout>
                <releases>
                    <enabled>true</enabled>
                    <updatePolicy>never</updatePolicy>
                </releases>
                <snapshots>
                    <enabled>true</enabled>
                    <updatePolicy>never</updatePolicy>
                </snapshots>
            </repository>
        </repositories>
        <pluginRepositories>
            <pluginRepository>
                <id>jboss-public-repository-group</id>
                <name>JBoss Public Maven Repository Group</name>
                <url>https://repository.jboss.org/nexus/content/groups/public/</url>
                <layout>default</layout>
                <releases>
                    <enabled>true</enabled>
                    <updatePolicy>never</updatePolicy>
                </releases>
                <snapshots>
                    <enabled>true</enabled>
                    <updatePolicy>never</updatePolicy>
                </snapshots>
            </pluginRepository>
        </pluginRepositories>
    </profile>
</profiles>
----
+
The profile then needs to be activated in the +<activeProfiles>+ element:
+
[source, XML]
----
<activeProfiles>
   <activeProfile>jboss-public-repository</activeProfile>
</activeProfiles>
----
+
For further details, refer to the *_JBoss RichFaces Wiki_* .

. Generate the project from the archetype
+
The project can now be generated with the _richfaces-archetype-simpleapp_archetype. Create a new directory for your project, then run the following Maven command in the directory:
+
----
mvn archetype:generate -DarchetypeGroupId=org.richfaces.archetypes -DarchetypeArtifactId=richfaces-archetype-simpleapp -DarchetypeVersion=5.0.0-SNAPSHOT -DgroupId=org.docs.richfaces -DartifactId=new_project
----
+
The following parameters can be used to customize your project:
+
_-DgroupId_:: Defines the package for the Managed Beans
_-DartifactId_:: Defines the name of the project
+

The command generates a new RichFaces project with the following structure:
+
----
new_project
	├── pom.xml
	├── readme.txt
	└── src
		└── main
		    ├── java
		    │   └── org
		    │       └── docs
		    │           └── richfaces
		    │               └── RichBean.java
		    └── webapp
		        ├── index.xhtml
		        ├── templates
		        │   └── template.xhtml
		        └── WEB-INF
		            ├── faces-config.xml
		            └── web.xml
----

. *Add test dependencies (optional)*
+
Your root directory of your project contains a project descriptor file, _pom.xml_. If you wish to include modules for test-driven JSF development, add any dependencies for the tests to the _pom.xml_file.
+
For testing server-side part of your implementation, check out link:$$http://www.jboss.org/arquillian$$[JBoss Arquillian project].
+
If you want to test JSF from client's perspective with ability to access state of JSF internals, use link:$$http://www.jboss.org/jsfunit$$[JBoss JSFUnit project] (with Arquillian integration).
+
For automation of client-side tests in real-browser, you may want to employ link:$$http://community.jboss.org/wiki/ArquillianAjocado$$[Arquillian Ajocado] and link:$$https://docs.jboss.org/author/display/ARQ/Drone$$[Arquillian Drone] extensions.
+
For mocking JSF environment, there is set of tools in RichFaces jsf-testproject. For full details on how to use the jsf-testproject, refer to article link:$$http://community.jboss.org/docs/DOC-13155$$[Test Driven JSF Development].

. *Build the project*
+
Build the project from the command line by entering the _mvn install_ command.
+
The +BUILD SUCCESSFUL+ message indicates the project has been assembled and is ready to import into an IDE (integrated development environment), such as JBoss Tools.

. *Import the project into an IDE*
+
To import the project into Eclipseand JBoss Tools, use the JBoss Maven Integration plug-ins. These plug-ins work with plug-ins from the M2Eclipse project to import Maven projects.

.. *Install the plug-ins*

... Choose HelpInstall New Softwarefrom the Eclipse menu.

... Select the JBoss Tools update site to use, then open the guilabel:[Maven Support] group and select the guilabel:[JBoss Maven Integration] and guilabel:[JBoss Maven JSF Configurator] plug-ins.

... Follow the prompts to install the integration plug-ins. The installation will automatically include the transitive dependencies guilabel:[Maven Integration for Eclipse] and guilabel:[Maven Integration for WTP] . Both of these dependencies are from the M2Eclipse project.

... Restart Eclipse to finish the installation.

.. *Open the importing wizard*
+
With the plug-ins installed, open the importing wizard by choosing File+>Import from the menu.

.. *Select the project*
+
Select Maven+>"Existing Maven Projects" as the import source and choose the directory with the _pom.xml_ file for your project.

[NOTE]
.Exporting from Maven
====
The ability to prepare the project for Eclipse and export it using Maven is deprecated in RichFaces 5.0.0-SNAPSHOT. The process does not support JBoss integration-specific features, such as JSF Facets.
====

Your project is now ready to use. Once components and functionality have been added, you can run the application on a server and access it through a web browser at the address _http://localhost:8080/jsf-app/_.

[[sect-Developer_Guide-Getting_started_with_RichFaces-Using_RichFaces_in_existing_JSF2_projects]]

=== Using RichFaces in existing JSF 2 projects

RichFaces can be added to existing JSF 2 projects by adding the new RichFaces libraries. Refer to <<step-Developer_Guide-Creating_a_project-Add_the_RichFaces_libraries_to_the_project, Step 2>> and <<step-Developer_Guide-Creating_a_project-Reference_the_tag_libraries, Step 3>> in <<sect-Developer_Guide-Getting_started_with_RichFaces-Creating_a_project_with_JBoss_Tools>> for details.

[NOTE]
.Application-level settings
====
In RichFaces 4, it is not necessary to add any extra settings to the _web.xml_or _config.xml_ settings files to use the framework.
====

[[chap-Developer_Guide-RichFaces_overview]]

== RichFaces overview

Read this chapter for technical details on the RichFaces framework.

[[sect-Component_Reference-RichFaces_overview-Full_technical_requirements]]

=== Full technical requirements

RichFaces has been developed with an open architecture to be compatible with a wide variety of environments.

[[sect-Component_Reference-RichFaces_overview-Server_requirements]]

==== Server requirements

RichFaces 4 requires either of the following server technologies:

* An application server compliant with Java Platform, Enterprise Edition 6 ( JEE6or JEE6), such as JBoss Application Server 7.
* A major servlet container, such as Jetty 8or Apache Tomcat 7.


[[sect-Component_Reference-RichFaces_overview-Client_requirements]]

==== Client requirements

Clients accessing RichFaces applications require a web browser. For a list of supported web browsers, refer to the link:$$https://community.jboss.org/wiki/PrioritizedRichFacesBrowsersCompatibilityMatrix$$[browser compatibility matrix] in the RichFaces wiki.

[[sect-Component_Reference-RichFaces_overview-Development_requirements]]

==== Development requirements

Developing applications with the RichFaces framework requires the Java Development Kit ( JDK), an implementation of JavaServer Faces ( JSF), and a development environment.

Java Development Kit (JDK)::
RichFaces supports the following JDK versions:
+
* JDK 1.6 and higher

JavaServer Faces (JSF):: RichFaces supports the following JSF implementations and frameworks:
+
* MyFaces 2.x
* Seam 3.x
* Mojara 2.x

Development environment:: RichFaces can be developed using most Java development environments.  The following are recommended, and used for examples in this guide:
+
* JBoss Tools 3.3 and higher
* Maven 3.0.3 and higher


[[sect-Developer_Guide-RichFaces_overview-Architecture]]

=== Architecture

The important elements of the RichFaces framework are as follows:

* Ajax Action Components
* Ajax Containers
* Ajax Output
* Skins and Theming
* RichFaces Ajax Extensions


Read this section for details on each element.

[[sect-Developer_Guide-Architecture-Ajax_Action_Components]]

==== Ajax Action Components

The RichFaces framework includes several Ajax Action Components and Submitting Bahaviors: +<a4j:commandButton>+, +<a4j:commandLink>+, +<a4j:poll>+, +<a4j:ajax>+, and more. Use Ajax Action Components to send Ajax requests from the client side.

[[sect-Developer_Guide-Architecture-Ajax_Containers]]

==== Ajax Containers

+AjaxContainer+ is an interface that marks part of the JSF tree that is decoded during an Ajax request. It only marks the JSF tree if the component or behavior sending the request does not explicitly specify an alternative. +AjaxRegion+ is an implementation of this interface.

[[sect-Developer_Guide-Architecture-Ajax_Output]]

==== Ajax Output

+AjaxContainer+ is an interface that marks part of the JSF tree that will be updated and rendered on the client for every Ajax request. It only marks the JSF tree if the component or behavior sending the request does not explicitly turn off automatic updates.

[[sect-Developer_Guide-Architecture-Skins_and_theming]]

==== Skins and theming

RichFaces includes extensive support for application skinning. Skinning is a high-level extension to traditional CSS(Cascading Style Sheets) which allows the color scheme and appearance of an application to be easily managed. The skins simplify look-and-feel design by allowing multiple elements of the interface to be handled as manageable features, which have associated color palettes and styling. Application skins can additionally be changed on the fly during run-time, allowing user experiences to be personalized and customized.

For full details on skinning and how to create skins for the components in your application, refer to <<chap-Developer_Guide-Skinning_and_theming>>.

[[sect-Developer_Guide-Architecture-RichFaces_Ajax_Extensions]]

==== RichFaces Ajax Extensions

The RichFaces Ajax Extensions plug in to the standard JSF 2 Ajax script facility. They extend the script facility with new features and options.

[[sect-Developer_Guide-RichFaces_overview-Technologies]]

=== Technologies

RichFaces 4 features full JSF 2 integration and uses standard web application technologies such as JavaScript, XML(Extensible Markup Language), and XHTML(Extensible Hypertext Markup Language).

[[sect-Developer_Guide-RichFaces_overview-Differences_between_JSF_and_RichFaces_mechanisms]]

=== Differences between JSFand RichFaces mechanisms

JavaServer Faces 2 evaluates Ajax options, such as +execute+ and +render+, while rendering a page. This allows any parameters to be sent directly from the client side.

RichFaces evaluates the options when the current request is sent. This increases both the security of the data and the convenience for evaluating parameters.

For example, binding Ajax options to Java Bean properties in RichFaces allows you to evaluate the options dynamically for the current request, such as defining additional zones to render. Parameters changed manually on the client side will not influence the request processing. With JSF 2, the options have evaluated during the previous page rendering would need to be used.

[[sect-Developer_Guide-RichFaces_overview-Restrictions]]

=== Restrictions

The following restrictions apply to applications implementing the RichFaces framework:

* As with most Ajax frameworks, you should not attempt to append or delete elements on a page using RichFaces Ajax, but should instead replace them. As such, elements that are rendered conditionally should not be targeted in the +render+ attributes for Ajax controls. For successful updates, an element with the same identifier as in the response must exist on the page. If it is necessary to append code to a page, include a placeholder for it (an empty element).

* JSF 2 does not allow resources such as JavaScript or Cascading Style Sheets ( CSS) to be added if the element requiring the resource is not initially present in the JSF tree. As such, components added to the tree via Ajax must have any required resources already loaded. In RichFaces, any components added to the JSF tree should have components with corresponding resources included on the main page initially. To facilitate this, components can use the +rendered="false"+ setting to not be rendered on the page.

* JSF does render resource links (stylesheets, scripts) in order of occurence, thus if you add +<h:outputStylesheet>+ to the +<h:head>+ section, JSF will render it before the RichFaces resource links (dependencies of RichFaces components). To be able to overwrite RichFaces stylesheets and re-use RichFaces JavaScript implementation, you need to render +<h:outputStylesheet target="head">+ to the +<h:body>+ section (safe solution is to place it on the end of the section; however to keep readability, you can use start of the section).

* Switching RichFaces skins via Ajax during runtime should be avoided, as this requires all the stylesheets to be reloaded.

[[chap-Developer_Guide-Basic_concepts]]

== Basic concepts

Read this chapter for the basic concepts of using RichFaces in conjunction with Ajax and JavaServer Faces.

[[sect-Developer_Guide-Basic_concepts-Sending_an_Ajax_request]]

=== Sending an Ajax request

Many of the tags in the +a4j+ and +rich+ tag libraries are capable of sending Ajax requests from a JavaServer Faces (JSF) page.

* The +<a4j:commandButton>+ and +<a4j:commandLink>+ tags are used to send an Ajax request on the +click+ JavaScript event.
* The +<a4j:poll>+ tag is used to send an Ajax request periodically using a timer.
* The +<a4j:ajax>+ tag allows you to add Ajax functionality to standard JSF components and send Ajax request on a chosen JavaScript event, such as +keyup+ or +mouseover+, for example.
* Most components in the +rich+ tag library have built-in Ajax support. Refer to the *_RichFaces Component Reference_* for details on the use of each component.


[[sect-Developer_Guide-Basic_concepts-Partial_tree_processing]]

=== Partial tree processing

Use the +execute+ attribute to specify which parts of the JSF tree to process during an Ajax request. The +execute+ attribute can point to an +id+ identifier of a specific component to process. Components can also be identified through the use of Expression Language ( EL).

Alternatively, the +execute+ attribute accepts the following keywords:

+@all+:: Every component is processed.
+@none+:: No components are processed.
+@this+:: The requesting component with the +execute+ attribute is processed.
+@form+:: The form that contains the requesting component is processed.
+@region+:: The region that contains the requesting component is processed. Use the +<a4j:region>+ component as a wrapper element to specify regions.
Some components make use of additional keywords. These are detailed under the relevant component entry in the *_RichFaces Component Reference_* .

[[sect-Developer_Guide-Basic_concepts-Partial_view_updates]]

=== Partial view updates

Use the +render+ attribute to specify which components to render for an Ajax update. The +render+ attribute can point to an +id+ identifier of a specific component to update. Components can also be identified through the use of Expression Language ( EL).

Alternatively, the +render+ attribute accepts the following keywords:

+@all+:: Every component is updated.
+@none+:: No components are updated.
+@this+:: The requesting component with the +execute+ attribute is updated.
+@form+:: The form that contains the requesting component is updated.
+@region+:: The region that contains the requesting component is updated. Use the +<a4j:region>+ component as a wrapper element to specify regions.

Some components make use of additional keywords. These are detailed under the relevant component entry in the *_RichFaces Component Reference_* .

Use the +<a4j:outputPanel>+ component with the +ajaxRendered="true"+ setting to always update a section irrespective of the requesting component's +render+ attribute. The +<rich:message>+ and +<rich:messages>+ components are based on the +<a4j:outputPanel>+ component, and as such will also always be updated. To override this behavior, use the +limitRender="true"+ setting on the requesting component.

[[sect-Developer_Guide-Basic_concepts-Component_overview]]

=== Component overview

The RichFaces framework is made up of two tag libraries: the +a4j+ library and the +rich+ library. The +a4j+ tag library represents _Ajax4jsf_, which provides page-level Ajax support with core Ajax components. This allows developers to make use of custom Ajax behavior with existing components. The +rich+ tag library provides Ajax support at the component level instead, and includes ready-made, self-contained components. These components don't require additional configuration in order to send requests or update.

For details on the use of the various components, refer to *_RichFaces Component Reference_* .

[[chap-Developer_Guide-Advanced_features]]

== Advanced features

Read this chapter for details on some of the advanced features and configuration possibilities for the RichFaces framework.

[[sect-Developer_Guide-Advanced_features-JSF2_integration]]

=== JSF 2 integration

JavaServer Faces ( JSF) is the Java-based web application framework upon which the RichFaces framework has been built. RichFaces is now integrated with JSF 2, which features several improvements to the framework.

* The standard display technology used by JSF 1 was JavaServer Pages ( JSP). With JSF 2, the standard display technology has been changed to Facelets, which is a more powerful and more efficient View Declaration Language ( VLD) than JSP.


[[sect-Developer_Guide-Advanced_features-Error_handling]]

=== Error handling

RichFaces allows standard handlers to be defined for processing different application exceptions. Custom JavaScript can be executed when these exceptions occur.

[[sect-Developer_Guide-Advanced_features-Client-side_errors]]

==== Client-side errors

JSF provides a global +onError+ handler on the client. The handler provides the relevant error code and other associated data. The RichFaces Ajax components provide the +error+ attribute if extra functionality needs to be defined.

Additional processing is available through a number of components, such as the following:

* The +<a4j:status>+ component has an additional error state.
* The +<a4j:queue>+ component can be used to process errors.


[[sect-Developer_Guide-Advanced_features-Server-side_errors]]

==== Server-side errors

Use the JSF 2 +ExceptionHandler+ class to handle server-side errors such as session expiration.

[[sect-Developer_Guide-Advanced_features-Other_functions]]

=== Other functions

RichFaces provides a number of advanced functions, such as managing user roles and identifying elements. Refer to the *_Functions_* chapter in the *_RichFaces Component Reference_* for further details.

[[sect-Developer_Guide-Advanced_features-Resource_loading]]

=== Resource loading

The RichFaces improves a standard JSF resource handling in order to achieve following features:

* resource optimization - serves optimized component resource dependencies (JavaScript, CSS)
* resource mapping - re-routes resource requests (maps an one resource to an another resource)


[[sect-Developer_Guide-Advanced_features-Configuring_ResourceServlet]]

==== Configuring ResourceServlet

For leveraging RichFaces resource loading improvements, the +ResourceServlet+ needs to be registered.

+ResourceServlet+ is automatically registered in the Servlet 3.0 and higher environments.

In the Servlet 2.5 and lower environments, it is necessary to register the +ResourceServlet+ manually in the +WEB-INF/web.xml+ configuration file:


[source, XML]
----
<servlet>
    <servlet-name>Resource Servlet</servlet-name>
    <servlet-class>org.richfaces.webapp.ResourceServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
</servlet>

<servlet-mapping>
    <servlet-name>Resource Servlet</servlet-name>
    <url-pattern>/org.richfaces.resources/*</url-pattern>
</servlet-mapping>
----

[[sect-Developer_Guide-Advanced_features-Resource_optimization]]

==== Resource optimization

The resource optimization feature provides optimized component dependencies - JavaScript, CSS - which are compressed and aggregated to resource packages.

The loading of compressed resource packages may lead into significant client performance boost, since many small files are aggregated into one big file - the number of HTTP connections necessary to download application resources is significantly decreased.

.Enabling resource optimization
====

To enable the resource optimization, add a following configuration to +web.xml+:


[source, XML]
----
<context-param>
    <param-name>org.richfaces.resourceOptimization.enabled</param-name>
    <param-value>true</param-value>
</context-param>
----

====

.Resource optimization in development JSF project stage
====

Resource optimization is influenced by the project stage:

* resources are not compressed in the development stage and during unit-testing to enable client-side debugging
* resources are compressed in the production stage and during a system-testing to minimize network bandwidth


Switch to the development project stage during a development:


[source, XML]
----
<context-param>
    <param-name>javax.faces.PROJECT_STAGE</param-name>
    <param-value>Development</param-value>
</context-param>
----

====

[[sect-Developer_Guide-Advanced_features-Resource_mapping]]

==== Resource mapping

The resource mapping feature maps an existing JSF resource (determined by library and name) to a another resource.

This feature can help to solve the following cases:

* providing alternative versions of JSF resources
* map several JSF resources to one
* using external resources
* moving resources to servers serving static content


===== Resource mapping configuration file

Configuring the resource mapping means adding new records to the class-path file +META-INF/richfaces/static-resource-mappings.properties+.

Each line in the configuration file represents one relocation.

A following sample shows a JSF resource with the name +resourceLibrary:resourceName+ relocated to a resource +anotherResourceLibrary:anotherResourceName+:

----
resourceLibrary\:resourceName=anotherResourceLibrary/anotherResourceName
----

[NOTE]
.Mapping resource name to relative URL
====
The definition above contains a JSF resource name on the left side of the expression and a relative path on the right side.

The expression on the right side represents a path relative to a JSF resource root, thus resource path +anotherResourceLibrary/anotherResourceName+ actually maps to a JSF resource with name +anotherResourceLibrary:anotherResourceName+.
====

[NOTE]
.Additional mapping files
====
It is possible to define additional resource mapping configuration files by using a contextual parameter identifying the class-path locations where the files reside: +org.richfaces.resourceMapping.mappingFile+ (a comma-separated list of the class-path files).
====

===== Examples of resource mapping

.Providing alternative file
====

All requests for +jquery.js+ are served as requests for +jquery-alternative-version.js+:

----
jquery.js=jquery-alternative-version.js
----

====

.Mapping several resources to one
====

Both +some:jquery.js+ and +another:jquery.js+ are mapped to +final:jquery.js+:

----
some\:jquery.js=final/jquery.js
another\:jquery.js=final/jquery.js
----

====

.Using external resources
====

Mappings with a resource path starting with +http://+ or +https://+ are served as absolute resource locations:

A following sample instructs to load +jquery.js+ from CDN:

----
jquery.js=http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
----

====

[[chap-Developer_Guide-Skinning_and_theming]]

== Skinning and theming

Read this chapter for a guide to skinning and theming RichFaces applications, including how to implement themes, and details on customizing and extending skins.

[[sect-Developer_Guide-Skinning_and_theming-What_are_skins]]

=== What are skins?

Application skins are used with the RichFaces framework to change the appearance of an application through setting the colors and decoration of controls and components. Typically the appearance of web applications is handled through the CSS(Cascading Style Sheet) files associated with the application, but skinning allows the settings in a CSS file to be abstracted and easily edited. Skins consist of a small, generalized set of font and color parameters that can be applied to multiple different styles. This avoids repetitive coding and duplication in CSS files. CSS files are not completely replaced: skins work as a high-level extension to standard CSS.

Each skin has a set of +skin-parameters+, which are used to define the theme palette and other elements of the user interface. These parameters work together with regular CSS declarations, and can be referred to from within CSS using JavaServer Faces Expression Language ( EL).

The skinning feature of RichFaces also allows skins to be changed at runtime, so users can personalize an application's appearance on the fly.

[[sect-Developer_Guide-Skinning_and_theming-Using_skins]]

=== Using skins

RichFaces includes a number of predefined skins. These skins can be used in RichFaces web applications by specifying the skin name in the +org.richfaces.skin+ context parameter in the _web.xml_ settings file. The predefined skins are as follows:

* +DEFAULT+
* +plain+, which contains no skin parameters and is intended for embedding RichFaces components into existing projects with their own styles.
* +emeraldTown+
* +blueSky+
* +wine+
* +japanCherry+
* +ruby+
* +classic+
* +deepMarine+


To add one of these skins to your application, add the +org.richfaces.SKIN+ context parameter to the _web.xml_ configuration file:

[source, XML]
----
<context-param>
    <param-name>org.richfaces.skin</param-name>
    <param-value>skin_name</param-value>
</context-param>
----

[[sect-Developer_Guide-Skinning_and_theming-Skinning_overview]]

=== Skinning overview

RichFaces skins are implemented using the following three-level scheme:

Component stylesheets:: Stylesheets are provided for each component. CSS style parameters map to skin parameters defined in the skin property file. This mapping is accomplished through the use of ECSS files. Refer to <<sect-Developer_Guide-Skinning_and_theming-ECSS_files>> for details on ECSS files.

Skin property files:: Skin property files map skin parameters to constant styles. Skin properties are defined in _skin.properties_ files. Refer to <<sect-Developer_Guide-Skinning_overview-Skin_parameter_tables>> for a listing of the skin parameters used in a typical skin.

Custom style classes:: Individual components can use the +styleClass+ attribute to redefine specific elements. These components then use the styles defined in a CSS file instead of the standard look for components as defined by the ECSS stylesheets.
[[sect-Developer_Guide-Skinning_overview-Skin_parameter_tables]]

==== Skin parameter tables

<<tabl-Developer_Guide-Skin_parameter_tables_in_RichFaces-Parameter_settings_for_the_blueSky_skin>> lists the default values for the parameter settings in the +blueSky+ skin. These values are all listed in the _blueSky.skin.properties_file, which can be customized and extended as described in <<sect-Developer_Guide-Skinning_and_theming-Customizing_skins>>.

[[tabl-Developer_Guide-Skin_parameter_tables_in_RichFaces-Parameter_settings_for_the_blueSky_skin]]

.Parameter settings for the +blueSky+ skin
[options="header"]
|===============
|Parameter name|Default value
|+headerBackgroundColor+|+#BED6F8+
|+headerGradientColor+|+#F2F7FF+
|+headTextColor+|+#000000+
|+headerWeightFont+|+bold+
|+generalBackgroundColor+|+#FFFFFF+
|+generalTextColor+|+#000000+
|+generalSizeFont+|+11px+
|+generalFamilyFont+|+Arial, Verdana, sans-serif+
|+controlTextColor+|+#000000+
|+controlBackgroundColor+|+#FFFFFF+
|+additionalBackgroundColor+|+#ECF4FE+
|+shadowBackgroundColor+|+#000000+
|+shadowOpacity+|+1+
|+panelBorderColor+|+#BED6F8+
|+subBorderColor+|+#FFFFFF+
|+calendarWeekBackgroundColor+|+#F5F5F5+
|+calendarHolidaysBackgroundColor+|+#FFEBDA+
|+calendarHolidaysTextColor+|+#FF7800+
|+calendarCurrentBackgroundColor+|+#FF7800+
|+calendarCurrentTextColor+|+#FFEBDA+
|+calendarSpecBackgroundColor+|+#E4F5E2+
|+calendarSpecTextColor+|+#000000+
|+editorBackgroundColor+|+#F1F1F1+
|+editBackgroundColor+|+#FEFFDA+
|+errorColor+|+#FF0000+
|+gradientType+|+plain+
|+tabBackgroundColor+|+#C6DEFF+
|+tabDisabledTextColor+|+#8DB7F3+
|+tableHeaderBackgroundColor+|+#D6E6FB+
|+tableSubHeaderBackgroundColor+|+#ECF4FE+
|+tableBorderWidth+|+1px+
|+tableHeaderTextColor+|+#0B356C+
|+trimColor+|+#D6E6FB+
|+tipBackgroundColor+|+#FAE6B0+
|+tipBorderColor+|+#E5973E+
|+selectControlColor+|+#E79A00+
|+generalLinkColor+|+#0078D0+
|+hoverLinkColor+|+#0090FF+
|+visitedLinkColor+|+#0090FF+
|+headerSizeFont+|+11px+
|+headerFamilyFont+|+Arial, Verdana, sans-serif+
|+tabSizeFont+|+11px+
|+tabFamilyFont+|+Arial, Verdana, sans-serif+
|+buttonSizeFont+|+11px+
|+buttonFamilyFont+|+Arial, Verdana, sans-serif+
|+tableBackgroundColor+|+#FFFFFF+
|+tableFooterBackgroundColor+|+#CCCCCC+
|+tableSubfooterBackgroundColor+|+#F1F1F1+
|+tableBorderColor+|+#C0C0C0+
|+warningColor+|+#FFE6E6+
|+warningBackgroundColor+|+#FF0000+
|===============

[[sect-Developer_Guide-Skinning_and_theming-Round_corners]]

==== Support for round corners

Support for round borders in your skins is available via the +panelBorderRadius+ skin parameter. The value of this parameter maps to the CSS 3 +border-radius+ property. This CSS 3 property is ignored in older browsers, and the skin gracefully degrades to square corners.

Units of the +panelBorderRadius+ skin parameter must be either +px+ (pixels). or +%+ (a percentage).

[[sect-Developer_Guide-Skinning_and_theming-ECSS_files]]

==== ECSSfiles

RichFaces uses ECSSfiles to add extra functionality to the skinning process. ECSS files are CSS files which use Expression Language ( EL) to connect styles with skin properties.

[[exam-Developer_Guide-Skinning_and_theming-ECSS_style_mappings]]

.ECSS style mappings
====

The ECSS code for the +<rich:panel>+ component contains styles for the panel and its body:


[source, Java]
----
.rf-p{
   background-color:'#{richSkin.generalBackgroundColor}';
   color:'#{richSkin.panelBorderColor}';
   border-width:1px;
   border-style:solid;
   padding:1px;
}

.rf-p-b{
   font-size:'#{richSkin.generalSizeFont}';
   color:'#{richSkin.generalTextColor}';
   font-family:'#{richSkin.generalFamilyFont}';
   padding:10px;
}

----

+.rf-p+  defines the panel styles::
+
* The background-colorCSS property maps to the +generalBackgroundColor+ skin parameter.
* The colorCSS property maps to the +panelBorderColor+ skin parameter.


+.rf-p-b+  defines the panel body styles::
+
* The font-familyCSS property maps to the +generalFamilyFont+ skin parameter.
* The font-sizeCSS property maps to the +generalSizeFont+ skin parameter.
* The colorCSS property maps to the +generalTextColor+ skin parameter.


====

[[sect-Developer_Guide-Skinning_and_theming-Customizing_skins]]

=== Customizing skins

Skins in RichFaces can be customized on each of the three levels:

Skin property files:: Application interfaces can be modified by altering the values of skin parameters in the skin itself. Edit the constant values defined in the _skin.properties_file to change the style of every component mapped to that skin property.
Component stylesheets:: Mappings and other style attributes listed in a component's ECSS file can be edited. Edit the ECSS file to change the styles of all components of that type.
Custom components style classes:: Individual components can use the +styleClass+ attribute to use a unique style class. Add the new style class to the application CSS and reference it from an individual component with the +styleClass+ attribute.
Overwriting stylesheets in application:: You can load custom stylesheets using +<h:outputStylesheet>+ which rewrites of extends styles defined for style classes of components.
[NOTE]
.Customizing skins by rewriting/extending component style classes
====
If you want to extend/overwrite style sheet definitions with own stylesheets, make sure you place definitions to be rendered in right order of occurence (see <<sect-Developer_Guide-RichFaces_overview-Restrictions,Restrictions>> section for details).
====

[[exam-Developer_Guide-Using_skins-Simple_skinning_example]]

.Simple skinning example
====

Using any component, such as a panel, without specifying a +styleClass+ will use the default skin parameters for that component.


[source, XML]
----
<rich:panel>This is a panel without a header</rich:panel>
----

When rendered for display, the panel consists of two HTML elements: a wrapper +<div>+ element and a +<div>+ element for the body of the panel. The wrapper element for a panel without a specified +styleClass+ is rendered as follows:


[source, XML]
----
<div id="..." class="rf-p">
   <div id="..." class="rf-p-b">
      This is a panel without a header
   </div>
</div>

----

To customize the panel appearance according to the three-level scheme, adjust the styles according to the following approach:

. Change the definitions for the +generalBackgroundColor+ or +panelBorderColor+ parameters in the skin. This will cause all panels in the application to change to the new settings.

. Redefine the +rf-p+ class in the application CSS. This will also cause all panels in the application to change to the new settings, though the skin itself has not been altered. Any properties not mapped to skin parameters should be redefined in this way.

. Specify a different +styleClass+ attribute to style the individual component. If a +styleClass+ attribute is used, the specified style class is applied to the component, which could extend or override the default styles.
+
[source, XML]
----
<rich:panel styleClass="customClass">...</rich:panel>
----
+
The +customClass+ style is added to the CSS, and is applied to the component when it is rendered for display:
+
[source, XML]
----
<div class="rf-p customClass">
   ...
</div>
----

====

[[sect-Developer_Guide-Customizing_skins-Creating_a_new_skin]]

==== Creating a new skin

. *Create the skin file*
+
The name of the skin file should follow the format _$$new_skin_name.skin.properties$$_and is placed in either the _META-INF/skins/_ directory or the classpath directory of your project.

. *Define the skin constants*
+
* *Define all the skin constants*
+
Add skin parameter constants and values to the file. All the skin parameters listed in <<tabl-Developer_Guide-Skin_parameter_tables_in_RichFaces-Parameter_settings_for_the_blueSky_skin>> should be included in the skin file, with settings relevant to your new skin.
+
[[exam-Developer_Guide-Skinning_and_theming-blueSky.skin.properties_file]]
._blueSky.skin.properties_file
====

Open the _blueSky.skin.properties_file from the _/META-INF/skins_ directory in the richfaces-impl-_++version++_.jarpackage. The file lists all the skin parameter constants shown in <<tabl-Developer_Guide-Skin_parameter_tables_in_RichFaces-Parameter_settings_for_the_blueSky_skin>>.

You can use the _blueSky.skin.properties_ file as a template for your new skin.

====
+
* *Extend a base skin*
+
Instead of redefining an entire new skin, your skin can use an existing skin as a base on which to build new parameters. Specify a base skin by using the +baseSkin+ parameter in the skin file, as shown in <<exam-Developer_Guide-Skinning_and_theming-Using_a_base_skin>>.
+
[[exam-Developer_Guide-Skinning_and_theming-Using_a_base_skin]]
.Using a base skin
====

This example takes the +blueSky+ skin as a base and only changes the +generalSizeFont+ parameter.

----
baseSkin=blueSky
generalSizeFont=12pt
----

====

. *Reference the skin definition*
+
Add a skin definition +<context-param>+ to the _web.xml_ settings file of your application:
+
[source, XML]
----
<context-param>
   <param-name>org.richfaces.skin</param-name>
   <param-value>new_skin_name</param-value>
</context-param>
----

[[sect-Developer_Guide-Skinning_and_theming-Changing_skins_at_runtime]]

=== Changing skins at runtime

To allow users to change skins at runtime, use a managed bean to access the skin.

. *Create the skin bean*
+
The skin bean is a simple interface to manage the skin:
+
[source, Java]
----
public class SkinBean {

    private String skin;

    public String getSkin() {
        return skin;
    }
    public void setSkin(String skin) {
        this.skin = skin;
    }
}

----

. *Reference the skin bean*
+
Add the +@ManagedBean+ and +@SessionScoped+ references to the class.
+
* Alternatively, use EL(Expression Language) to reference the skin bean from the _web.xml_ settings file.
+
[source, XML]
----
<context-param>
    <param-name>org.richfaces.skin</param-name>
    <param-value>#{skinBean.skin}</param-value>
</context-param>
----

. *Set initial skin*
+
The application needs an initial skin to display before the user chooses an alternative skin. Specify the skin in your class with +@ManagedProperty+.
+
[source, Java]
----
@ManagedProperty(value="blueSky")
private String skin;
----
+
* Alternatively, specify the initial skin in the _web.xml_ configuration file.
+
[source, XML]
----
<managed-bean>
    <managed-bean-name>skinBean</managed-bean-name>
    <managed-bean-class>SkinBean</managed-bean-class>
    <managed-bean-scope>session</managed-bean-scope>
    <managed-property>
        <property-name>skin</property-name>
        <value>blueSky</value>
    </managed-property>
</managed-bean>
----

[[sect-Developer_Guide-Skinning_and_theming-Skinning_standard_controls]]

=== Skinning standard controls

Standard HTML controls used alongside RichFaces components are also themed to create a cohesive user interface.

[[sect-Developer_Guide-Skinning_standard_controls-Automatic_skinning]]

==== Automatic skinning

The skinning style properties are automatically applied to controls based on their element names and attribute types. If the HTML elements are referenced in the standard skin stylesheets, the controls will be styled according to the mapped skin properties.

Standard HTML controls are skinned in this way by default. To override this behavior and prevent the RichFaces skins from being applied to the standard HTML controls, set the +org.richfaces.enableControlSkinning+ context parameter in the _web.xml_ configuration file to +false+:


[source, XML]
----
<context-param>
   <param-name>org.richfaces.enableControlSkinning</param-name>
   <param-value>false</param-value>
</context-param>
----

[[sect-Developer_Guide-Skinning_standard_controls-Skinning_with_the_rfs-ctn_class]]

==== Skinning with the +rfs-ctn+ class

The skinning style properties can be determined through a separate CSS class. This method is not available by default, but is enabled through the +org.richfaces.enableControlSkinningClasses+ context parameter in the _web.xml_ configuration file:


[source, XML]
----
<context-param>
   <param-name>org.richfaces.enableControlSkinningClasses</param-name>
   <param-value>true</param-value>
</context-param>
----

When enabled, a stylesheet with predefined classes offers a special CSS class named +rfs-ctn+. Reference the +rfs-ctn+ class from any container element (such as a +<div>+ element) to skin all the standard HTML controls in the container.

Standard HTML controls can also be specifically defined in the CSS. Refer to the _$$/core/impl/src/main/resources/META-INF/resources/skinning_both.ecss$$_file in the richfaces-ui.jarpackage for examples of specially-defined CSS classes with skin parameters for HTML controls.

[[appe-Developer_Guide-Style_classes_and_skin_parameters]]


[appendix]
== Style classes and skin parameters

Each of the RichFacescomponents are listed below, along with their style classes and skin parameters. For further details on each component, refer to the relevant section in the *_RichFaces Component Reference_* .

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Processing_management]]

=== Processing management

[[sect-Developer_Guide-Style_classes_and_skin_parameters-a4jlog]]

==== +<a4j:log>+

include::skinning/tabl-a4jlog.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Rich_inputs]]

=== Rich inputs

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richautocomplete]]

==== +<rich:autocomplete>+

include::skinning/tabl-richautocomplete.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richcalendar]]

==== +<rich:calendar>+

include::skinning/tabl-richcalendar.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richeditor]]

==== +<rich:editor>+

include::skinning/tabl-richeditor.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richfileUpload]]

==== +<rich:fileUpload>+

include::skinning/tabl-richfileUpload.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richinplaceInput]]

==== +<rich:inplaceInput>+

include::skinning/tabl-richinplaceInput.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richinputNumberSlider]]

==== +<rich:inputNumberSlider>+

include::skinning/tabl-richinputNumberSlider.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richinputNumberSpinner]]

==== +<rich:inputNumberSpinner>+

include::skinning/tabl-richinputNumberSpinner.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Rich_selects]]

=== Rich selects

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richinplaceSelect]]

==== +<rich:inplaceSelect>+

include::skinning/tabl-richinplaceSelect.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richselect]]

==== +<rich:select>+

include::skinning/tabl-richselect.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richorderingList]]

==== +<rich:orderingList>+

include::skinning/tabl-richorderingList.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richspickList]]

==== +<rich:pickList>+

include::skinning/tabl-richpickList.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Panels_and_containers]]

=== Panels and containers

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richpanel]]

==== +<rich:panel>+

include::skinning/tabl-richpanel.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richaccordion]]

==== +<rich:accordion>+

include::skinning/tabl-richaccordion.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richcollapsiblePanel]]

==== +<rich:collapsiblePanel>+

include::skinning/tabl-richcollapsiblePanel.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richpopupPanel]]

==== +<rich:popupPanel>+

include::skinning/tabl-richpopupPanel.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richtabPanel]]

==== +<rich:tabPanel>+

include::skinning/tabl-richtabPanel.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Tables_and_grids]]

=== Tables and grids

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richdataTable]]

==== +<rich:dataTable>+

include::skinning/tabl-richdataTable.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richcollapsibleSubTable]]

==== +<rich:collapsibleSubTable>+

include::skinning/tabl-richcollapsibleSubTable.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richcollapsibleSubTableToggler]]

==== +<rich:collapsibleSubTableToggler>+

include::skinning/vlst-richcollapsibleSubTableToggler.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richextendedDataTable]]

==== +<rich:extendedDataTable>+

include::skinning/tabl-richextendedDataTable.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richdataGrid]]

==== +<rich:dataGrid>+

include::skinning/tabl-richdataGrid.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richlist]]

==== +<rich:list>+

include::skinning/tabl-richlist.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richdataScroller]]

==== +<rich:dataScroller>+

include::skinning/tabl-richdataScroller.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Trees]]

=== Trees

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richtree]]

==== +<rich:tree>+

include::skinning/vlst-richtree.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richtreeNode]]

==== +<rich:treeNode>+

include::skinning/tabl-richtreeNode.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Menus_and_toolbars]]

=== Menus and toolbars

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richdropDownMenu]]

==== +<rich:dropDownMenu>+

include::skinning/tabl-richdropDownMenu.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richcontextMenu]]

==== +<rich:contextMenu>+

include::skinning/tabl-richcontextMenu.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richpanelMenu]]

==== +<rich:panelMenu>+

include::skinning/tabl-richpanelMenu.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richtoolbar]]

==== +<rich:toolbar>+

include::skinning/tabl-richtoolbar.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Output_and_messages]]

=== Output and messages

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richmessage]]

==== +<rich:message>+

include::skinning/tabl-richmessage.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richmessages]]

==== +<rich:messages>+

include::skinning/tabl-richmessages.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richnotify]]

==== +<rich:notify>+

include::skinning/tabl-richnotify.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richnotifyMessage]]

==== +<rich:notifyMessage>+

include::skinning/tabl-richnotifyMessage.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richnotifyStack]]

==== +<rich:notifyStack>+

include::skinning/tabl-richnotifyStack.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richprogressBar]]

==== +<rich:progressBar>+

include::skinning/tabl-richprogressBar.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richtooltip]]

==== +<rich:tooltip>+

include::skinning/tabl-richtooltip.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-Drag_and_drop]]

=== Drag and drop

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richdropTarget]]

==== +<rich:dropTarget>+

include::skinning/vlst-richdropTarget.asciidoc[]

[[sect-Developer_Guide-Style_classes_and_skin_parameters-richdragIndicator]]

==== +<rich:dragIndicator>+

include::skinning/vlst-richdragIndicator.asciidoc[]

[[appe-Developer_Guide-Migration_Notes]]

[appendix]
== Migration Notes

This section of the guide will track any breaking changes introduced in new releases, and identify any steps required to accommodate those changes in your application.

[[appe-Developer_Guide-Migration_Notes-4_3_0]]

=== RichFaces 4.3.0.Final

[[appe-Developer_Guide-Migration_Notes-4_3_0-built_in_sorting_and_filtering_controls]]

==== Built-in sorting and filtering controls

The +<extendedDataTable>+ now has built-in sorting and filtering controls. If you have existing +<extendedDataTable>+ with custom sort and/or filter controls, you will want to disable the built-in sort and/or filter controls. This can be done either on a column-by-column basis, or for all columns in your applications.

For details on disabling the built-in sort and filter controls, refer to sections "External filter controls" and "External sort controls" in the RichFaces Component Reference.

[[appe-Developer_Guide-Migration_Notes-4_3_0-NotifyMessage_Sting_Escaping]]

==== NotifyMessage string escaping

Prior to version 4.3.0.Final, the message summary and details of the +<rich:notifyMessage>+ and +<rich:notifyMessages>+ components were not escaped. In the 4.3.0.Final release, an attribute +escape+ was added with a default value true.

[[appe-Developer_Guide-Migration_Notes-4_3_0-Select_Input_Validation]]

==== Select input validation

The +<rich:select>+ now validates that manually entered input values match one of the values of the provided list (including support for client-side validation).

[[appe-Developer_Guide-Revision_History]]
